### PR TITLE
Add transcript like the one in Youtube.

### PR DESCRIPTION
**Pull request by cyj98**
I just add the transcript module to look up the word and excerpt quickly. It works like the one on Youtube. 
1. It will change currentTime when clicking on the transcript text.
2. It always highlights the text of currentTime.
3. Transcript text will scroll to the text of the currentTime when the pointer does not hover on the transcript.

I think the transcript is a good selling point for some language learners like me.
By the way, I limit adding the subtitle to only one video so I don’t need extra code to make transcript work on multiple videos. I don’t think any user will watch two videos with subtitles at the same time. If you don't like it, I will change it.

Edited:
More features:
1. support more websites(can work on videos in a nested iframe).
2. delete in the video list if the video is removed(sometimes the advertisement has the video tag and will be removed)
3. fix some warnings on vue-eslint/recommend and format some files using prettier.
4. change the popup position on click
5. scroll to the center of the video when hovering on the video card if the video is not in the viewport(learn from substital)

### CODE REVIEW

**Comment by cyj98** [comment]
This is made mainly for my own purpose. It you don’t like it, just close the pull request and I will move it to my own branch.

**Comment by ste-xx** [comment]
Sounds really interesting.
I will have a look and will give you feedback.

**Comment by ste-xx** [comment]
I REALLY like the transcript feature, but it seams that it does not work correctly with the offset.

**Comment by cyj98** [comment]
Nice, thanks for the feedback.
Just fix the offset problem in the transcript window by changing the parsed to withOffsetParsed.

**Comment by cyj98** [comment]
I know the meaning of the excerpt component now. I just don't know how to use it previously. I think it's also very useful.

**Pull request merged**
